### ISSUE TITLE
yarn install fail

### ISSUE THREAD

**Issue by ilumer** [alibaba/lightproxy#11]
yarn-error.log
```
Error: https://registry.npm.alibaba-inc.com/monaco-editor-webpack-plugin/download/monaco-editor-webpack-plugin-1.7.0.tgz: ETIMEDOUT
 at Timeout._onTimeout (/usr/local/Cellar/yarn/1.17.0/libexec/lib/cli.js:141099:19)
 at listOnTimeout (internal/timers.js:531:17)
 at processTimers (internal/timers.js:475:7)
```
yarn config list
```
{
  'version-tag-prefix': 'v',
  'version-git-tag': true,
  'version-commit-hooks': true,
  'version-git-sign': false,
  'version-git-message': 'v%s',
  'init-version': '1.0.0',
  'init-license': 'MIT',
  'save-prefix': '^',
  'bin-links': true,
  'ignore-scripts': false,
  'ignore-optional': false,
  registry: 'https://registry.npm.taobao.org',
  'strict-ssl': false,
  'user-agent': 'yarn/1.17.0 npm/? node/v12.5.0 darwin x64',
  lastUpdateCheck: 1577698269175,
  'sass-binary-site': 'http://npm.taobao.org/mirrors/node-sass'
}
```
删除yarn.lock 可以下载依赖成功，但在yarn run dev时会提醒electron安装失败要求重新安装

**Comment by xcodebuild** [comment]
已经删除 `yarn.lock` 了

试试看

```shell
rm -rf node_modules
npm run install-deps
npm run dev
```

`install-deps` 期间会从下载 `electron` 的 `pre-built`，需要确保下载成功了

如果确实无法安装成功，可以参考 `https://juejin.im/post/5db48591f265da4d4c201c6d` 使用镜像安装 `eletron`

**Comment by ilumer** [comment]
electron 安装失败参考 `https://github.com/cnpm/cnpmjs.org/issues/1519`
