### ISSUE TITLE
Install deps failed - 404 not found on https://npm.taobao.org/mirrors/electron/10.1.5/electron-v19.0.4-linux-x64.zip

### ISSUE THREAD

**Issue by kamuridesu** [alibaba/lightproxy#285]
```
error /home/kamuri/Documentos/workspace/personal/tools/lightproxy/node_modules/electron: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /home/kamuri/Documentos/workspace/personal/tools/lightproxy/node_modules/electron
Output:
HTTPError: Response code 404 (Not Found) for https://npm.taobao.org/mirrors/electron/10.1.5/electron-v19.0.4-linux-x64.zip
    at EventEmitter.<anonymous> (/home/kamuri/Documentos/workspace/personal/tools/lightproxy/node_modules/got/source/as-stream.js:35:24)
    at EventEmitter.emit (events.js:400:28)
    at module.exports (/home/kamuri/Documentos/workspace/personal/tools/lightproxy/node_modules/got/source/get-response.js:22:10)
    at ClientRequest.handleResponse (/home/kamuri/Documentos/workspace/personal/tools/lightproxy/node_modules/got/source/request-as-event-emitter.js:155:5)
    at Object.onceWrapper (events.js:520:26)
    at ClientRequest.emit (events.js:412:35)
    at ClientRequest.origin.emit (/home/kamuri/Documentos/workspace/personal/tools/lightproxy/node_modules/@szmarczak/http-timer/source/index.js:37:11)
```

**Comment by Muzlin** [comment]
electron-custom-dir=10.1.5
edit:
electron-custom-dir=v10.1.5

**Comment by nailuoGG** [comment]
如果网络畅通，可以删掉 .npmrc 文件
