### ISSUE TITLE
install package error

### ISSUE THREAD

**Issue by zzlhr** [alibaba/lightproxy#36]
```shell
# haoranliu @ iMac in ~/OpenSource/lightproxy on git:develop x [16:34:10]
$ cnpm install
✖ Install fail! Error: [whistle@./whistle] resolved target /Users/haoranliu/OpenSource/lightproxy/whistle error: ENOENT: no such file or directory, lstat '/Users/haoranliu/OpenSource/lightproxy/whistle'
Error: [whistle@./whistle] resolved target /Users/haoranliu/OpenSource/lightproxy/whistle error: ENOENT: no such file or directory, lstat '/Users/haoranliu/OpenSource/lightproxy/whistle'
    at module.exports (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/download/local.js:30:11)
    at module.exports.throw (<anonymous>)
    at onRejected (/usr/local/lib/node_modules/cnpm/node_modules/co/index.js:81:24)
npminstall version: 3.23.0
npminstall args: /usr/local/Cellar/node/13.5.0/bin/node /usr/local/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js --fix-bug-versions --china --userconfig=/Users/haoranliu/.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://r.npm.taobao.org
```

根目录package.json使用了`./whistle` 但是根目录没有whistle文件夹
```
"update:whistle": "rm -rf whistle && git clone https://github.com/avwo/whistle --depth=1 && patch -u -b whistle/lib/inspectors/res.js -i whistle.patch && yarn add ./whistle ./whistle-start",
```

**Comment by xcodebuild** [comment]
使用 npm run install-deps 来初始化依赖
